2022-05-17 22:39:19,759 ERROR 42500 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Sequence._packetToError (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 42500
hostname: litian-mbp

2022-05-17 22:40:06,846 ERROR 42613 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Sequence._packetToError (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 42613
hostname: litian-mbp

2022-05-17 22:42:29,753 ERROR 43106 [-/127.0.0.1/-/11ms GET /default/getArticleList] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'article.last_updated' in 'field list'
    at Sequence._packetToError (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at proto._query (/Users/litian/blog/services/node_modules/ali-rds/lib/client.js:38:20)
    at proto.query (/Users/litian/blog/services/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/litian/blog/services/node_modules/co/index.js:65:19)
    at /Users/litian/blog/services/node_modules/co/index.js:54:5
    sql: SELECT article.id as id,article.title as title,article.brief as brief,FROM_UNIXTIME(article.last_updated,'%H:%i, %m/%d/%Y' ) as last_updated,article.view_count as view_count,category.name as category_name FROM article LEFT JOIN type ON article.category_id = category.id
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'article.last_updated' in 'field list'"
sqlState: "42S22"
index: 0
sql: "SELECT article.id as id,article.title as title,article.brief as brief,FROM_UNIXTIME(article.last_updated,'%H:%i, %m/%d/%Y' ) as last_updated,article.view_count as view_count,category.name as category_name FROM article LEFT JOIN type ON article.category_id = category.id"
name: "ER_BAD_FIELD_ERRORError"
pid: 43106
hostname: litian-mbp

2022-05-17 23:07:55,786 ERROR 43923 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 43923
hostname: litian-mbp

2022-05-17 23:10:36,838 ERROR 44018 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 44018
hostname: litian-mbp

2022-05-21 11:38:07,480 ERROR 10623 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 10623
hostname: litian-mbp

2022-05-21 11:38:37,275 ERROR 10691 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 10691
hostname: litian-mbp

2022-05-21 11:39:10,730 ERROR 10845 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 10845
hostname: litian-mbp

2022-05-21 16:33:57,673 ERROR 15479 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 15479
hostname: litian-mbp

2022-05-21 16:34:26,901 ERROR 15723 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 15723
hostname: litian-mbp

2022-05-21 16:34:30,714 ERROR 15747 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 15747
hostname: litian-mbp

2022-05-21 16:36:03,682 ERROR 15942 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 15942
hostname: litian-mbp

2022-05-21 16:36:15,317 ERROR 15979 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 15979
hostname: litian-mbp

2022-05-21 16:38:33,346 ERROR 16772 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 16772
hostname: litian-mbp

2022-05-21 16:43:57,689 ERROR 17361 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17361
hostname: litian-mbp

2022-05-21 16:46:37,356 ERROR 17450 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17450
hostname: litian-mbp

2022-05-21 16:47:09,585 ERROR 17495 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17495
hostname: litian-mbp

2022-05-21 16:48:13,585 ERROR 17546 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17546
hostname: litian-mbp

2022-05-21 16:50:00,426 ERROR 17620 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17620
hostname: litian-mbp

2022-05-21 16:51:13,557 ERROR 17979 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 17979
hostname: litian-mbp

2022-05-21 16:52:11,652 ERROR 18240 [-/127.0.0.1/-/0ms GET /] nodejs.ECONNREFUSEDError: connect ECONNREFUSED ::1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
    --------------------
    at Protocol._enqueue (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/litian/blog/services/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/litian/blog/services/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/litian/blog/services/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/litian/blog/services/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/litian/blog/services/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/litian/blog/services/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
errno: -61
code: "ECONNREFUSED"
syscall: "connect"
address: "::1"
port: 3306
fatal: true
name: "ECONNREFUSEDError"
pid: 18240
hostname: litian-mbp

